---
fabric_name: GLOBAL # it has to match the inventory group as mentioned here: https://avd.arista.com/devel/ansible_collections/arista/avd/roles/eos_designs/docs/data-models.html?h=fabric_name#fabric-topology-hierarchy

# fabric_numbering:
#   node_id:
#     algorithm: "pool_manager"

node_type_keys:
  - key: spines
    type: l3spine
    connected_endpoints: true
    mlag_support: true
    network_services:
      l2: true
      l3: true
    default_overlay_routing_protocol: none
    default_underlay_routing_protocol: none
    cv_tags_topology_type: spine
  # - key: l2subleaf
  #   type: l2leaf
  #   connected_endpoints: true
  #   default_evpn_role: none
  #   mlag_support: false
  #   network_services:
  #     l2: true
  #     l3: false
  #   vtep: false
  #   underlay_router: false
  #   uplink_type: port-channel
  #   cv_tags_topology_type: leaf
  - key: internet_leaf
    type: l2leaf
    connected_endpoints: true
    default_evpn_role: none
    mlag_support: false
    network_services:
      l2: true
      l3: false
    vtep: false
    underlay_router: false
    uplink_type: port-channel
    cv_tags_topology_type: leaf
  # - key: distribution_leaf
  #   type: l2leaf
  #   connected_endpoints: true
  #   default_evpn_role: none
  #   mlag_support: true
  #   network_services:
  #     l2: true
  #     l3: false
  #   vtep: false
  #   underlay_router: false
  #   uplink_type: port-channel
  #   cv_tags_topology_type: leaf
