---
USOFFICE1_SPINE:
- name: USOFFICE1_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - USOFFICE1_SPINE01
    - USOFFICE1_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
