---
INOFFICE2_SPINE:
- name: INOFFICE2_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - INOFFICE2_SPINE01
    - INOFFICE2_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
