---
INOFFICE1_SPINE:
- name: INOFFICE1_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - INOFFICE1_SPINE01
    - INOFFICE1_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
