---
USOFFICE3_SPINE:
- name: USOFFICE3_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - USOFFICE3_SPINE01
    - USOFFICE3_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
