---
USOFFICE3_LEAF01:
- name: USOFFICE3_LEAF01_Eth10
  adapters:
  - endpoint_ports:
    - LB01A
    - LB01B
    switches:
    - USOFFICE3_LEAF01A
    - USOFFICE3_LEAF01B
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
