---
USOFFICE2_LEAF01:
- name: USOFFICE2_LEAF01_Eth10
  adapters:
  - endpoint_ports:
    - LB01A
    - LB01B
    switches:
    - USOFFICE2_LEAF01A
    - USOFFICE2_LEAF01B
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
