---
UKOFFICE1_SPINE:
- name: UKOFFICE1_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - UKOFFICE1_SPINE01
    - UKOFFICE1_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
