---
UKOFFICE2_SPINE:
- name: UKOFFICE2_SPINE_Eth10
  adapters:
  - endpoint_ports:
    - FW01A
    - FW01B
    switches:
    - UKOFFICE2_SPINE01
    - UKOFFICE2_SPINE02
    switch_ports:
    - Ethernet10
    - Ethernet10
    profile: PP_TEST
