---
- name: Build Switch configuration
  hosts: [ all ]
  connection: local
  gather_facts: false
  collections:
    - arista.avd


  tasks:

    - name: generate intented variables
      tags: [ build ]
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      vars:
        eos_designs_keep_tmp_files: "{{ debug | default(false) }}"

    - name: generate device intended config and documentation
      tags: [ build, cli ]
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
