---
- name: Build Switch configuration
  hosts: [EMEA]
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  vars: 
    root_dir: '{{ playbook_dir }}'


  tasks:

    - name: generate intented variables
      tags: [ build ]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [ build, cli ]
      import_role:
        name: arista.avd.eos_cli_config_gen

