---
- name: Build Switch configuration
  hosts: [ all ]
  connection: local
  gather_facts: false
  collections:
    - arista.avd


  tasks:

    - name: generate intented variables
      tags: [ build ]
      vars:
        eos_designs_documentation:
          enable: false
          connected_endpoints: false
          topology_csv: false
          p2p_links_csv: false
          toc: false
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [ build, cli ]
      vars:
        eos_cli_config_gen_documentation:
          enable: false
          hide_passwords: false
          toc: false
      import_role:
        name: arista.avd.eos_cli_config_gen
